name = "Applications Setup"

[[data]]
name = "Bash Prompt"
command = "bash -c \"$(curl -s https://raw.githubusercontent.com/ChrisTitusTech/mybash/main/setup.sh)\""

[[data]]
name = "Kitty"
script = "kitty-setup.sh"